name: Update Readme with Latest Dev.to Posts

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get RSS feed
      run: |
        curl -s "https://dev.to/feed/${{ env.DEVTO_USERNAME }}" > devto.xml
      
    - name: Parse RSS feed and update readme
      run: |
        POSTS=$(cat devto.xml | grep -Eo '<link>(https://dev.to/[^<]*)' | cut -c7- | awk 'NR<6 {print}')
        sed -i "s%<!--START_SECTION:devto-->.*<!--END_SECTION:devto-->%<!--START_SECTION:devto-->\n$POSTS\n<!--END_SECTION:devto-->%" README.md

